version: "3.1"
services:
  db: #postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web: #node
    build: .
    command: npm run dev
    volumes:
      - ./src:/app/src
    ports:
      - 3333:3333
    depends_on:
      - db
    env_file:
      - .env

